"""add User.confirmed

Revision ID: d6a95ed3460f
Revises: 1507ba02d810
Create Date: 2016-01-19 21:14:21.142727

"""

# revision identifiers, used by Alembic.
revision = 'd6a95ed3460f'
down_revision = '1507ba02d810'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
